sonar.projectKey=Maneesh-Kumar-Maddini_8.2CDevSecOps
sonar.organization=Maneesh-Kumar-Maddini
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=app.js,routes,views
sonar.exclusions=node_modules/**,test/**,coverage/**,.scannerwork/**
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
